#pragma once
#include <Windows.h>
#include <iostream>
#include <SDL.h>
#include <GL/glew.h>
#include <GL/glfw3.h>
#include <GL/GL.h>
#include <GL/GLU.h>
#include <cstdlib>
#include <algorithm>
#include <cstdio>
#include <memory>
#include <fstream>
#include <istream>
#include <vector>
#include <string>